language: java
install: ""
script: 
    - "export TERM=dumb"
    - "cd guide/"
    - "./gradlew clean aim42 publish --stacktrace"
jdk:
    - openjdk7
env:
  global:
  - secure: "kbi5yQZ19ECqZJjbt3GWMbY6u/t3mMrOqGPeXX889EBk83fdOa+NAxwkYlZpkcSa0WAtbORprSmjkCYlQjlqZ4NNsZSgVUz1N1qeruXhweDN0yE6uvU4od6uZpt0BMJlSaLDhptYhT50x78i6UNE6Sru1Q/pkWwP+o1tYo0e3Rk="
