language: java
install: ""
script: 
    - "export TERM=dumb"
    - "cd guide/"
    - "./gradlew clean aim42 publish --stacktrace"
jdk:
    - openjdk7
env:
  global:
  - secure: NsYdysvLiBX1esW1XNQHn7TBsFDQOjxn6ztHJSo4pqji1zX9RKET+IIuDYSRVTQDe6s6vsIVb4xGbVbI1Co3Qn5hP9zvw8TzbDVCXrhjalgE1X+Xb6O9uI/I6Ri/YD1SiCIHuC4rSCzudvpIFh+mULpTTHfGiiGZ17CtbIKsUnw=

